version: 0.0
os: linux
files:
  - source: ./hugo-config/.
    destination: /git/personal-profile
hooks:
  AfterInstall:
    - location: deployment-scripts/build-website.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment-scripts/start-website.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: deployment-scripts/stop-website.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: deployment-scripts/validate-website.sh
      timeout: 30
      runas: root
      